name: Build Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
          sudo apt-get install graphviz
      - name: Pre-deploy
        id: prep
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
          RELEASE: ${{ github.event_name == 'release' && github.event.action == 'published' }}
          RELEASE_VERSION: ${{ github.event.release.tag_name }}

        run: |
          if [[ $RELEASE == "true" ]]; then
            echo "This is a release!"
            echo $RELEASE
            DOCNAME="${RELEASE_VERSION##*v}"
          elif [[ $BRANCH_NAME =~ "release" ]]; then
            echo "This is a release branch!"
            VERSION="${BRANCH_NAME##*/}"
            DOCNAME="${VERSION}-beta"
          elif [[ $BRANCH_NAME == "develop" ]]; then
            echo "This is the develop branch!"
            DOCNAME="develop"
          elif [[ $BRANCH_NAME == "main" ]]; then
            echo "This is the main branch!"
            DOCNAME="latest"
          else
            DOCNAME="${BRANCH_NAME}"
            echo "Not sure how to handle $BRANCH_NAME"
            exit 1
          fi
          echo "Using $DOCNAME"
          echo "DOCNAME=$DOCNAME" >> $GITHUB_OUTPUT
          echo "DEST_DIR=${DOCNAME%%-*}" >> $GITHUB_OUTPUT

      - name: Build docs
        run: |
          cd docs
          make html
          cd ..
          cp docs/source/versions.json docs/build/html/versions.json

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4        
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
          publish_branch: gh-pages
          destination_dir: ./${{ steps.prep.outputs.DEST_DIR }}
          keep_files: true
          force_orphan: true
      - name: Copy versions.json
        run: |
          git fetch
          git checkout gh-pages
          cp ${{ steps.prep.outputs.DEST_DIR }}/versions.json versions.json
          cp ${{ steps.prep.outputs.DEST_DIR }}/redirect.html index.html
          if [[ -z $(git status --porcelain) ]]; then
            echo "No changes"
          else
            git config user.name 'github-actions[bot]'
            git config user.email 'github-actions[bot]@users.noreply.github.com'
            git add versions.json
            git add index.html
            git commit -m "Update versions.json and index.html"
            git push origin gh-pages
          fi